stages:
    - deploy

# deploy kepler
build:
    stage: deploy
    only:
        variables:
            - $CI_COMMIT_MESSAGE =~ /\[deploy-kepler\]/
    tags:
        - kepler
        - www
    script:
        - cd /var/www/timber-computer
        - source ~/.bashrc
        - git fetch
        - git checkout $CI_COMMIT_REF_NAME
        - git pull
        - nvm use 16
        - npm install
        - cd frontend/
        - npm run build
    artifacts:
        paths:
            dist/

